project:
  type: website
  output-dir: ../docs/2026

website:
  title: "Optimización y Aprendizaje Automático II - 2026"

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "1. OPTIMIZACIÓN MATEMÁTICA"
        contents:
          - href: CAPITULO_1/A1_intro_optimizacion.qmd
            text: "1.1 Introducción a la optimización"
          - href: CAPITULO_1/A2_optimizacion_convexa.qmd
            text: "1.2 Optimización convexa"
          - href: CAPITULO_1/A3_programas_conicos.qmd
            text: "1.3 Programas cónicos"
          - href: CAPITULO_1/A4_condiciones_optimalidad.qmd
            text: "1.4 Condiciones de optimalidad"
          - href: CAPITULO_1/A5_metodos_optimizacion.qmd
            text: "1.5 Métodos de optimización"
  page-navigation: true  # Activar navegación entre páginas

format:
  live-html:
    pyodide:
      cell-options:
        edit: true
        include: true
    css: style.css
    toc: true
    toc-depth: 3
    toc-location: right
    toc-floating: true
# number-sections: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

lang: es