---
title: "Modelos lineales generalizados"
subtitle: "Capítulo 2 - Sección 3"
---
<hr style="border: 1px solid rgba(50, 0, 0, 1);">

{{< include ../macros.qmd >}}


<div class="d-flex align-items-center justify-content-between">

  <div class="d-flex gap-2">
    
  <a href="../material/apunte_c2s3.pdf" target="_blank" class="btn btn-outline-primary">
    <i class="fa-solid fa-file-lines me-2"></i>Versión PDF
  </a>

  <a href="../material/tp_c2s3.pdf" target="_blank" class="btn btn-outline-success">
    <i class="fa-solid fa-clipboard-list me-2"></i>Guía de actividades
  </a>

  </div>

  <span class="text-muted small">
    <i class="fa-solid fa-clock-rotate-left me-1"></i>
    Última actualización: 28/09/2026
  </span>

</div>

<div style="margin-top:20px"></div>



Tanto en el modelo de regresión lineal como en el de regresión logística, asumimos una cierta distribución condicional para $Y\mid\XX$ que depende de un vector de parámetros $\bftheta\in\RR^p$.

- En regresión lineal, $Y\mid\XX=\xx\sim\calN(\bftheta^\top\xx,\sigma^2)$.

- En regresión logística, $Y\mid\XX=\xx\sim\text{Bernoulli}(\sigma(\bftheta^\top\xx))$, con $\sigma:\RR\to\RR$ la función logística.

Además, vimos que en regresión logística, la incorporación del parámetro natural $\eta=\bftheta^\top \xx$ y de la función $A(\eta)=\log(1+e^\eta)$ permiten escribir la función de probabilidad condicional como
$$
p(y\mid\eta)=\exp\left\{\eta y-A(\eta)\right\}.
$$

Algo similar ocurre en regresión lineal si consideramos $\sigma^2=1$, $\eta=\bftheta^\top\xx$ y $A(\eta)=\eta^2/2$:
$$
p(y\mid\eta)=\frac{1}{\sqrt{2\pi}}e^{-(y-\eta)^2/2}=h(y)\exp\left\{\eta y-A(\eta)\right\},\qquad h(y)=\frac{1}{\sqrt{2\pi}}e^{-y^2/2}.
$$

La elección $\sigma^2=1$ es sin pérdida de generalidad ya que, como vimos, el estimador de máxima verosimilitud de $\bftheta$ no depende de $\sigma^2$. De hecho, es fácil ver que para $\sigma^2$ arbitrario se mantiene la estructura lineal tomando $\eta=\tilde{\bftheta}^\top\xx$, con $\tilde{\bftheta}=\bftheta/\sigma^2$.

Por último, es importante remarcar que en ambos modelos se cumple 
$$
A'(\eta)=\media\left[Y\mid\XX=\xx\right]\qquad\text{y}\qquad A''(\eta)=\var\left[Y\mid\XX=\xx\right],$$

y que la predicción es
$$
\hat{y}=h_{\hat{\bftheta}}(\xx):=\media\left[Y\mid\XX=\xx; \hat{\bftheta}\right],
$$
que resulta en $\hat{y}=\hat{\bftheta}^\top\xx$ en regresión lineal y $\hat{y}=\sigma\big(\hat{\bftheta}^\top\xx\big)$ en regresión logística.

<div style="margin-top:1.5em;"></div>


La estructura común de ambos modelos sugiere una generalización natural: elegir otras distribuciones con la misma forma para $Y\mid\XX$, manteniendo $\eta=\bftheta^\top\xx$. Esto conduce a los \textit{Modelos Lineales Generalizados} (GLM), una amplia familia de modelos que incluye a ambos como casos particulares y permite abordar una gran variedad de problemas de regresión y clasificación. Para estudiarlos, en primer lugar introduciremos formalmente la \textit{familia exponencial}, que agrupa a todas las distribuciones con esta forma e incluye muchas de las comúnmente utilizadas en estadística.


<div style="border-top:1px solid #b7cdf5;
            background-color: #fafbff;
            padding:0.1em 0;
            margin-top:1.5em;">

📄 **Notación**

Para el caso de un vector aleatorio $\bfZ\in\RR^q$ con distribución de probabilidad $\prob_{\bfZ}$, se definen el *vector de medias* $\media\left[\bfZ\right]\in\RR^q$ y la *matriz de covarianza* $\cov\left[\bfZ\right]\in\RR^{q\times q}$ como sigue:
$$
\media\left[\bfZ\right]:=\int \zz\,d\prob_{\bfZ}(\zz),
$$
$$
\cov\left[\bfZ\right]:=\media\left[(\bfZ-\media\left[\bfZ\right])(\bfZ-\media\left[\bfZ\right])^\top\right].
$$

</div>

<div style="margin-top:2.5em;"></div>



## I <span style="color:#CCCCCC;">│</span> La familia exponencial

::: {.definicion}
**Definición 2.3.1.** (Familia exponencial)  Decimos que una clase de distribuciones pertenece a la *familia exponencial* si se puede escribir en la forma

$$
p(y \mid \bfeta) := h(y) \exp\left\{\bfeta^\top T(y) - A(\bfeta)\right\},
\tag{2.3.1}
$$

con $h:\RR\to\RR$, $\bfeta\in\RR^q$, $T:\RR\to\RR^q$ y $A:\RR^q\to\RR$.

:::

<div style="margin-top:1em;"></div>


En la expresión (1) se distinguen los siguientes elementos:

- $\bfeta\in\RR^q$ es el *parámetro natural*.

- $T:\RR\to\RR^q$ es el *estadístico suficiente*.

- $h:\RR\to\RR$ es la *función base* que depende únicamente de $y$.

- $A:\RR^q\to\RR$ es la *función de log-partición* que normaliza la expresión, garantizando que la distribución integre a 1.


Para un mismo $h$ y $T$, la familia exponencial consiste en todas las distribuciones que se obtienen al variar el parámetro natural $\bfeta$. Observar que (2.3.1) puede expresarse también como
$$
p(y\mid\bfeta)=\frac{h(y)\exp\left\{\bfeta^\top T(y)\right\}}{\exp\left\{A(\bfeta)\right\}}=\frac{h(y)\exp\left\{\bfeta^\top T(y)\right\}}{\displaystyle\int h(y)\exp\left\{\bfeta^\top T(y)\right\}\,dy}.
\tag{2.3.2}
$$

lo cual resulta del hecho que $\int p(y\mid\bfeta)\,dy=1$.

<div style="margin-top:2em;"></div>


::: {.callout-example}
<span class="badge bg-primary">Ejemplo 2.3.2</span> 
<span style="color: #0d6efd; font-family: Arial; font-weight: bold; font-size: 0.85em;">
Distribución Bernoulli
</span>

Sea $Y\in\{0,1\}$ tal que $Y\sim\text{Binom}(1,\phi)$, con $\phi:=\prob(Y=1)$. Entonces
$$
p(y\mid\phi) = \phi^y(1-\phi)^{1-y}.
$$

De acuerdo a lo visto en regresión logística, la distribución de $Y$ se puede escribir como
$$
p(y\mid\phi) = \exp\left\{\eta y-A(\eta)\right\}.
$$
con parámetro natural
$$
\eta=\logit\phi=\log\left(\frac{\phi}{1-\phi}\right)\in\RR,
$$

y estadístico suficiente $T:\RR\to\RR$ definido por $T(y)=y$. Por lo tanto, la distribución Bernoulli es un miembro de la familia exponencial. El resto de los elementos son:
$$
h(y)=1,\qquad A(\eta)=-\log(1-\phi)=\log(1+e^\eta).
$$

:::

::: {.callout-example}
<span class="badge bg-primary">Ejemplo 2.3.3</span> 
<span style="color: #0d6efd; font-family: Arial; font-weight: bold; font-size: 0.85em;">
Distribución Normal univariada
</span>

Sea $Y\in\RR$ tal que $Y\sim\calN(\mu,\sigma^2)$. Entonces

$$
\begin{align*}
p(y \mid \mu, \sigma^2) & = \frac{1}{\sqrt{2\pi}\sigma} \exp\left\{-\frac{(y - \mu)^2}{2\sigma^2}\right\} \\[2pt]
& = \frac{1}{\sqrt{2\pi}}\exp\left\{-\frac{1}{2\sigma^2}y^2+\frac{\mu}{\sigma^2}y-\frac{\mu^2}{2\sigma^2}-\log\sigma\right\} \\[2pt]
& = \frac{1}{\sqrt{2\pi}}\exp\left\{\left(\frac{\mu}{\sigma^2},-\frac{1}{2\sigma^2}\right)^\top (y,y^2)-\frac{\mu^2}{2\sigma^2}-\log\sigma\right\}.
\end{align*}
$$

Por lo tanto, la distribución Normal univariada es un miembro de la familia exponencial, con parámetro natural

$$
\bfeta=\left(\frac{\mu}{\sigma^2},-\frac{1}{2\sigma^2}\right)\in\RR^2,
$$

y estadístico suficiente $T:\RR\to\RR^2$ definido por $T(y)=(y,y^2)$. El resto de los elementos son:
$$
h(y)=\frac{1}{\sqrt{2\pi}}, \qquad A(\bfeta)=\frac{\mu^2}{2\sigma^2}+\log\sigma=-\frac{\eta_1^2}{4\eta_2}+\frac{1}{2}\log(-2\eta_2).
$$

:::

::: {.callout .question}

<span style="font-size: 1em;">✍️</span><br>

Exprese la distribución normal univariada con varianza conocida como familia exponencial.

:::

<div style="margin-top:2em;"></div>


Existen muchas otras distribuciones que son miembros de la familia exponencial: la Multinomial (que veremos más adelante), la Poisson (para modelar datos de conteo), la Gamma y la Exponencial (para modelar variables continuas no negativas, como intervalos de tiempo) la Beta y la Dirichlet (para distribuciones sobre probabilidades), y muchas más. 

<div style="margin-top:2em;"></div>


<div class="alert alert-light text-dark" role="important">
<span class="badge bg-warning text-dark">Importante</span>

La función de partición $A:\RR^q\to\RR$ queda definida a partir de la siguiente expresión:
$$
A(\bfeta):=\log\int h(y)\exp\left\{\bfeta^\top T(y)\right\}\,dy.
$$

Se verifica que
$$
\nabla A(\bfeta)=\media\left[T(Y)\right]\in\RR^q,\qquad \nabla^2 A(\bfeta)=\cov\left[T(Y)\right]\in\RR^{q\times q}.
$$

<div style="margin-top:2em;"></div>

<details>
<summary><span style="color:#0056b3;">ℹ Ver más información</span></summary>

::: {.panel-tabset}

### <span style="border: 1px solid #ddd; padding: 2px 6px; border-radius: 4px;">*Demostración*</span>

Derivando respecto de $\bfeta$, resulta
$$
\nabla A(\bfeta)=\frac{\nabla\left[\displaystyle\int h(y)\exp\left\{\bfeta^\top T(y)\right\}\,dy\right]}{\displaystyle\int h(y)\exp\left\{\bfeta^\top T(y)\right\}\,dy}=\frac{\displaystyle\int h(y)\exp\left\{\bfeta^\top T(y)\right\}\, T(y)\,dy}{\displaystyle\int h(y)\exp\left\{\bfeta^\top T(y)\right\}\,dy},
$$

donde hemos asumido que la derivación bajo el signo integral es válida para $\bfeta$ en un conjunto abierto. De (2.3.2) resulta
$$
\nabla A(\bfeta)=\int T(y)\, p(y\mid\bfeta)\,dy=\media\left[T(Y)\right].
$$

Ahora bien, aplicando regla del cociente, resulta
$$
\begin{align*}
\nabla^2 A(\bfeta) &= \displaystyle\int T(y)T(y)^\top p(y\mid\bfeta)\,dy - \displaystyle\int T(y)\,p(y\mid\bfeta)\,dy \int T(y)^\top p(y\mid\bfeta)\,dy \\[3pt]
&=\media\left[T(Y) T(Y)^\top\right]-\media\left[T(Y)\right]\media\left[T(Y)\right]^\top \\[5pt]
&=\cov\left[T(Y)\right].
\end{align*}
$$

:::
</details>

<div style="margin-top:1.5em;"></div>

::: {.myhighlight}
De lo anterior resulta que $\nabla^2 A(\bfeta)\succeq 0$, lo cual significa que $A$ es una función convexa.
:::

</div>

::: {.callout .question}

<span style="font-size: 1.3em;">✍️</span><br>

¿Cuándo $A$ es estrictamente convexa?

:::

<div style="margin-top:2em;"></div>


::: {.callout-example}
<span class="badge bg-primary">Ejemplo 2.3.4</span> 
<span style="color: #0d6efd; font-family: Arial; font-weight: bold; font-size: 0.85em;">
Gradiente y Hessiana de $A(\bfeta)$ para las distribuciones Bernoulli y Normal univariada
</span>

Vamos a verificar la expresión de $\nabla A(\bfeta)$ y $\nabla^2 A(\bfeta)$ para los casos de las distribuciones Bernoulli y Normal univariada, utilizando las expresiones obtenidas en los ejemplos 2.3.2 y 2.3.3.

- Si $Y\sim\text{Bernoulli}(\phi)$, entonces
    $$
    A'(\eta)=\frac{e^{\eta}}{1+e^{\eta}}=\frac{\frac{\phi}{1-\phi}}{\frac{1}{1-\phi}}=\phi=\media\left[Y\right],
    $$
    $$
    A''(\eta)=\frac{e^{\eta}}{(1+e^{\eta})^2}=\frac{\frac{\phi}{1-\phi}}{\frac{1}{(1-\phi)^2}}=\phi(1-\phi)=\cov\left[Y\right].
    $$

- Para la distribución Normal univariada serán de utilidad sus momentos. Si $Y\sim\calN(\mu,\sigma^2)$, se tiene que
    $$
    \media\left[Y\right]=\mu,\qquad\media\left[Y^2\right]=\mu^2+\sigma^2
    $$
    $$
    \media\left[Y^3\right]=\mu^3+3\mu\sigma^2,\qquad \media\left[Y^4\right]=\mu^4+6\mu^2\sigma^2+3\sigma^4.
    $$

    Ahora sí derivamos:
    $$
    \nabla A(\bfeta)=\left(-\frac{\eta_1}{2\eta_2},\frac{\eta_1^2}{4\eta_2^2}-\frac{1}{2\eta_2}\right)^\top=(\mu,\mu^2+\sigma^2)^\top=\media\left[(Y,Y^2)\right]=\media\left[T(Y)\right],
    $$
    $$
    \nabla^2 A(\bfeta)=\begin{pmatrix}
    -\displaystyle\frac{1}{2\eta_2} & \displaystyle\frac{\eta_1}{2\eta_2^2} \\
    \displaystyle\frac{\eta_1}{2\eta_2^2} & -\displaystyle\frac{\eta_1^2}{2\eta_2^3}+\frac{1}{2\eta_2^2}
    \end{pmatrix} =\begin{pmatrix}
    \sigma^2 & 2\mu\sigma^2 \\ 
    2\mu\sigma^2 & 4\mu^2\sigma^2+2\sigma^4
    \end{pmatrix}=\cov\left[T(Y)\right],
    $$
    donde para esta última igualdad se usaron las igualdades 
    $$
    \var\left[Y^2\right]=\media\left[Y^4\right]-\media\left[Y\right]^2,\qquad\cov\left[Y,Y^2\right]=\media\left[Y^3\right]-\media\left[Y\right]\,\media\left[Y^2\right].
    $$

:::

<div style="margin-top:2.5em;"></div>



## II <span style="color:#CCCCCC;">│</span> Modelo lineal generalizado

Supongamos que deseas construir un modelo para estimar el número $y$ de clientes que llegan a tu tienda (o el número de visitas a páginas web en tu sitio) en una hora determinada, basándote en ciertas características como promociones en la tienda, publicidad reciente, clima, día de la semana, etc. Sabemos que la distribución Poisson usualmente proporciona un buen modelo para el número de visitantes. Sabiendo esto, ¿cómo podemos proponer un modelo para nuestro problema? Afortunadamente, la Poisson es una distribución de la familia exponencial, por lo que podemos aplicar un Modelo Lineal Generalizado (GLM). En esta sección, describiremos un método para construir modelos GLM para problemas como este.

En forma general, consideremos un problema de regresión o clasificación donde queremos predecir el valor de alguna variable aleatoria $Y\in\RR$ a partir de un conjunto de predictoras $\XX\in\RR^p$. La familia exponencial será nuestra herramienta para modelar las distribuciones condicionales $Y\mid\XX$. De hecho, formalmente un GLM queda definido a partir del siguiente supuesto:


::: {.myhighlight2 style="color: rgb(204, 0, 0);"}

<span style="font-size:0.8em;">*Supuesto del modelo*</span>

$Y\mid\XX=\xx$ sigue una distribución perteneciente a la familia exponencial, con parámetro natural de la forma

<div style="margin-top:-0.5em;"></div>

$$
\bfeta:=\bfTheta^\top\xx,\qquad\bfTheta\in\RR^{p\times q}.
$$

:::

<div style="margin-top:1em;"></div>

El parámetro natural $\bfeta\in\RR^q$ queda conectado a la función de regresión $\media\left[T(Y)\mid \xx;\bfTheta\right]$ a partir de una *función de enlace canónica* $g:\RR^q\to\RR^q$ que verifica
$$
\bfeta=g\left(\media\left[T(Y)\mid\xx;\bfTheta\right]\right).
$$

<div style="margin-top:2em;"></div>


::: {.callout-example}
<span class="badge bg-primary">Ejemplo 2.3.5</span> 
<span style="color: #0d6efd; font-family: Arial; font-weight: bold; font-size: 0.85em;">
Función de enlace en regresión logística
</span>

En regresión logística, el estadístico suficiente es $T(y)=y$. Además, sabemos que
$$
\eta=\bftheta^\top\xx,\qquad \media\left[Y\mid\xx;\bftheta\right]=h_{\bftheta}(\xx)=\sigma(\bftheta^\top\xx)
$$

Es decir, $\media\left[Y\mid\xx;\bftheta\right]=\sigma(\eta)$. Por lo tanto,
$$
\eta=\sigma^{-1}\left(\media\left[Y\mid\xx;\bftheta\right]\right).
$$

Así, la función de enlace canónica para regresión logística es la función inversa de la función logística, a saber $\logit: (0,1)\to\RR$, definida por
$$
\logit p:=\log\frac{p}{1-p}.
$$

:::

::: {.callout .question}

<span style="font-size: 1em;">✍️</span><br>

Determine la función de enlace canónica para regresión lineal.

:::

<div style="margin-top:2em;"></div>


En un GLM la estructura del modelo hace que, una vez estimado $\bftheta$, todo lo demás se
obtiene por composición. El estimador $\hat{\bftheta}$ conduce a un estimador del parámetro
natural, $\hat{\bfeta}(\xx)=\hat{\bftheta}^\top \xx$, y este, a su vez, determina la función de regresión:
$$
\media\left[T(Y)\mid \xx;\hat{\bftheta}\right]= \nabla A\!\left(\hat{\bfeta}(\xx)\right).
$$

En conclusión:

::: {.myhighlight}
El modelo GLM nos permite predecir
$$
\hat{y}=h_{\hat{\bfTheta}}(\xx):=\media\left[T(Y)\mid\xx;\hat{\bfTheta}\right].
$$
:::

<div style="margin-top:1.5em;"></div>


::: {.callout .question}

<span style="font-size: 1.3em;">✍️</span><br>


Analice el GLM del ejemplo inicial de esta sección, en el que se modela el número de visitantes a una tienda. ¿Cuál es la función de enlace canónica? ¿Qué predice el modelo?

:::

<div style="margin-top:2.5em;"></div>


A continuación, vamos a abordar el problema de estimación de los parámetros en un GLM de la
manera habitual: definiendo el problema de optimización a partir del principio de máxima
verosimilitud y luego, de ser posible, aplicando una condición de optimalidad. Por razones de
simplicidad, supondremos
$$
\eta=\bftheta^\top\xx\in\RR,\qquad \bftheta\in\RR^p.
$$

Además, para una muestra $\{(\xx_i,y_i)\}_{i=1}^n$ i.i.d., denotamos
$$
\eta_i:=\bftheta^\top\xx_i,$$
$$
\mu_i:=\media\left[T(Y)\mid \XX=\xx_i;\bftheta\right]=\nabla A(\eta_i).
$$



<div style="margin-top:2em;"></div>



### Función de verosimilitud

De (2.3.1) resulta
$$
\log p(y_i\mid\eta)=\log(h(y))+\eta\, T(y_i)-A(\eta).
$$

Por lo tanto, la función de log-verosimilitud es
$$
\ell(\bftheta)=\sum_{i=1}^n\left[\eta_i\, T(y_i)-A(\eta_i)\right]+\text{cte}.
\tag{2.3.3}
$$

<div style="margin-top:1.5em;"></div>



### Optimalidad

De (2.3.3), el problema de optimización resultante es
$$
\begin{array}{ll}
	\text{minimizar } & \underbrace{\displaystyle\sum_{i=1}^n\left[A(\eta_i)-\eta_i\, T(y_i)\right]}_{J(\bftheta)}
\end{array}
\tag{2.3.4}
$$

El vector gradiente de la función de costo $J$ es
$$
\nabla J(\bftheta)=\sum_{i=1}^n\left[A'(\eta_i)-T(y_i)\right]\xx_i=X^\top\left[A'(\tilde{\bfeta})-T(\yy)\right],
\tag{2.3.5}
$$

donde $A'(\tilde{\bfeta})=(A'(\eta_1),\ldots,A'(\eta_n))^\top\in\RR^n$ y $T(\yy)=(T(y_1),\ldots,T(y_n))\in\RR^n$, mientras que la matriz Hessiana resulta
$$
\nabla^2 J(\bftheta)=\sum_{i=1}^n A''(\eta_i)\xx_i\xx_i^\top = X^\top W X,
\tag{2.3.6}
$$

donde $W=\diag(A''(\eta_1),\ldots,A''(\eta_n))\in\RR^{n\times n}$. Observar que la matriz $W$ actúa como una matriz de pesos: el peso de la $i$-ésima observación es
$A''(\eta_i)=\cov\left[T(Y)\mid\xx_i;\bftheta\right]$, que en general depende
de $\bftheta$ y de $\xx_i$. En el caso de la regresión lineal (varianza constante) estos pesos
son todos iguales y se recupera $X^\top X$ salvo una constante; en cambio, en un GLM general
los pesos varían entre observaciones y con $\bftheta$.


::: {.callout .question}

<span style="font-size: 1.3em;">✍️</span><br>

Justifique la convexidad de la función objetivo $J(\bftheta)$ en (2.3.4).

:::

<div style="margin-top:2em;"></div>


Dado que tenemos convexidad, podemos plantear $\nabla J(\bftheta)=\bfzero$. De (2.3.5) y por propiedad de la derivada de la función de log-partición $A$, podemos escribir
$$
\sum_{i=1}^n\left(\media\left[T(Y)\mid\XX=\xx_i\right]-T(y_i)\right)\,\xx_i=\bfzero.
$$

Observar que lo del paréntesis es el *residuo* entre el valor observado de $T(y_i)$ y su valor esperado según el modelo. La condición de optimalidad establece que, en el óptimo, el vector de residuos es ortogonal a cada una de las columnas de $X$: los
residuos no están correlacionados (en sentido muestral) con ninguno de los predictores del modelo. En particular, si estamos trabajando con la matriz ampliada $\tilde{X}$, los residuos suman cero.

En general, no existe una solución explícita para el punto óptimo $\hat{\bftheta}$, y ni siquiera está garantizado que exista: la convexidad asegura que todo punto con $\nabla J(\bftheta)=\bfzero$ es un mínimo global, pero la existencia depende de la familia y de los datos observados. Cuando existe, se aproxima mediante métodos iterativos; como conocemos el gradiente y la Hessiana de $J$, el método de Newton resulta una opción natural y da lugar a un algoritmo muy eficiente.

<div style="margin-top:2em;"></div>



### Resolución por método de Newton: algoritmo IRLS


Recordemos que el método de Newton actualiza los parámetros mediante
$$
\bftheta_{t+1}:=\bftheta_t-\left[\nabla^2 J(\bftheta_t)\right]^{-1}\nabla J(\bftheta_t).
\tag{2.3.7}
$$

Su aplicación al problema (2.3.4) deriva en un algoritmo denominado IRLS (*Iterative Reweighted Least Squares*), que se basa en resolver iterativamente problemas de mínimos cuadrados ponderados (WLS, *weighted least squares*). Para obtenerlo, reemplacemos en (2.3.7) las expresiones (2.3.5) y (2.3.6) obtenidas para el gradiente y la Hessiana de $J$; resulta
$$
\bftheta_{t+1}:=\bftheta_t+(X^\top W_t X)^{-1}X^\top\left[T(\yy)-A'(\tilde{\bfeta}_t)\right]
\tag{2.3.8}
$$

<div style="margin-top:2em;"></div>


<div class="alert alert-light text-dark" role="important">
<span class="badge bg-success text-light">Reinterpretación de Newton como WLS</span>

El paso de Newton (\ref{eq:newton_glm_explicito}) puede leerse como la solución de un problema de mínimos cuadrados ponderados (WLS). En efecto, dados $W_t=\operatorname{diag}(A''(\eta_{t,1}),\ldots,A''(\eta_{t,n}))$ y $\zz_t\in\RR^n$, la solución de
$$
\begin{array}{ll}
	\text{minimizar } & \displaystyle\frac{1}{2}\|W_t^{1/2}(\zz_t-X\bftheta)\|_2^2
\end{array}
$$

es $(X^\top W_t X)^{-1}X^\top W_t\zz_t$. Se busca entonces una \textit{pseudo-respuesta} $\zz_t$ tal que
$$
\bftheta_{t+1}=(X^\top W_t X)^{-1}X^\top W_t\zz_t.
\tag{2.3.9}
$$

Definimos
$$
z_{t,i}:=\eta_{t,i}+\frac{T(y_i)-\mu_{t,i}}{w_{t,i}},\qquad i=1,\ldots,n,
$$

con $\eta_{t,i}=\xx_i^\top\bftheta_t$, $\mu_{t,i}=A'(\eta_{t,i})$ y $w_{t,i}=A''(\eta_{t,i})$. Como $W_t$ cancela el denominador $w_{t,i}$,
$$
X^\top W_t\zz_t=X^\top W_t X\bftheta_t+\sum_{i=1}^n\big(T(y_i)-\mu_{t,i}\big)\xx_i .
$$

Multiplicando por $(X^\top W_t X)^{-1}$ resulta
$$
(X^\top W_t X)^{-1}X^\top W_t\zz_t=\bftheta_t+(X^\top W_t X)^{-1}X^\top\big[T(\yy)-A'(\tilde{\bfeta}_t)\big],
$$

que es exactamente (2.3.8). Por lo tanto, (2.3.8) y (2.3.9) son equivalentes.

</div>

<div style="margin-top:2em;"></div>


Así, cada iteración de Newton equivale a resolver un problema de mínimos cuadrados ponderados con pesos $W_t$ y pseudo-respuesta $\zz_t$, ambos recalculados en cada paso. No se trata de un algoritmo distinto, sino de otra forma de leer el mismo paso, y esa lectura tiene varias ventajas. Por un lado, permite interpretar el ajuste de un GLM como una sucesión de regresiones lineales ponderadas. Por otro, permite reutilizar solvers de mínimos cuadrados, que resuelven el problema de forma numéricamente estable (por ejemplo, con QR o Cholesky sobre $W_t^{1/2}X$) sin formar explícitamente $X^\top W_t X$. Repitiendo el procedimiento se aproxima el estimador de máxima verosimilitud, aprovechando la curvatura de $J$ para dar pasos más precisos que un simple descenso por gradiente.

<div style="margin-top:2em;"></div>


<div class="alert alert-light text-dark" role="important">
⚙ <span class="badge bg-custom">Algoritmo IRLS</span>

---

Dado un *parámetro inicial* $\bftheta_0\in\RR^{p}$:

<div style="margin-left: 1em">

$t\leftarrow 0.$

**repetir**:

> **1°** Calcular $\tilde{\bfeta}_t=X\bftheta_t$ y $\bfmu_t\in\RR^n$ tal que $\mu_{t,i}=A'(\eta_{t,i})=\media\left[T(Y)\mid\XX=\xx_i;\bftheta_t\right]$.
>  
> **2°** Construir la matriz diagonal de pesos $W_t\in\RR^{n\times n}$ tal que $w_{t,i}=A''(\eta_{t,i})=\var\left[T(Y)\mid\XX=\xx_i;\bftheta_t\right]$..  
>
> **3°** Definir la pseudo-respuesta $\zz_t=\tilde{\bfeta}_t+W_t^{-1}\left(T(\yy)-\bfmu_t\right)$.
>
> **4°** Actualizar $\bftheta_{t+1}:=(X^\top W_t X)^{-1}X^\top W_t\zz_t$.
>
> $t\leftarrow t+1$.

**hasta** que el criterio de parada se satisfaga.

</div>

---
</div>

<div style="margin-top:2em;"></div>


::: {.callout-example}
<span class="badge bg-primary">Ejemplo 2.3.6</span> 
<span style="color: #0d6efd; font-family: Arial; font-weight: bold; font-size: 0.85em;">
Algoritmo IRLS para regresión logística
</span>

En regresión logística, dada la matriz de predictoras $X\in\RR^{n\times p}$ y el vector de respuestas $\yy\in\RR^n$, el algoritmo IRLS se implementa de la siguiente manera. A partir del valor actual $\bftheta_t$, en la siguiente iteración se calculan:

- El vector $\tilde{\bfeta}_t=X\bftheta_t\in\RR^n$.

- El vector de medias $\bfmu_t=\sigma(\tilde{\bfeta}_t)\in\RR^n$ tal que $\mu_{t,i}=\sigma(\bftheta_t^\top\xx_i)$.

- La matriz de pesos $W_t\in\RR^{n\times n}$ tal que
    $$
    w_{t,i} = \sigma(\eta_{t,i})(1-\sigma(\eta_{t,i}), \qquad i=1,\ldots,n.
    $$

- La pseudo-respuesta
    $$
    \zz_t=\tilde{\bfeta}_t+W_t^{-1}(\yy-\bfmu_t)\in\RR^n.
    $$

Finalmente, se actualiza el vector de parámetros a $\bftheta_{t+1}$ a partir de la solución del problema de mínimos cuadrados ponderados con pesos $W$ y pseudo-respuesta $\zz$, determinada por la expresión (2.3.9).

:::

<div style="margin-top:2.5em;"></div>



## III <span style="color:#CCCCCC;">│</span> Regresión softmax

Consideremos un problema de clasificación en el que $Y \in \{1, 2, \ldots, k\}$. Por ejemplo, en lugar de clasificar correos electrónicos en dos clases (spam o no spam), podríamos clasificarlos en tres clases: spam, correo personal y correo relacionado con el trabajo. Para modelar esta situación, usaremos la *distribución multinomial* con un único ensayo (también llamada *distribución categórica*)  como un elemento de la familia exponencial. De esta manera, podremos construir un modelo GLM para clasificación multiclase, conocido como *regresión softmax* o *regresión logística multinomial*, que generaliza la regresión logística binaria a problemas con más de dos clases.

<div style="margin-top:2em;"></div>


::: {.callout-example}
<span class="badge bg-primary">Ejemplo 2.3.7</span> 
<span style="color: #0d6efd; font-family: Arial; font-weight: bold; font-size: 0.85em;">
Distribución categórica
</span>

Sea $Y\in\RR$ tal que $Y\sim\text{Multinomial}(1,\bfphi)$, con $\bfphi\in\RR^k$ tal que $\sum_{i=1}^k\phi_i=1$. Entonces
$$
p(y\mid\bfphi)=\phi_1^{\bfone\{y=1\}}\phi_2^{\bfone\{y=2\}}\ldots \phi_k^{\bfone\{y=k\}},
$$

donde $\bfone\{\cdot\}$ es la función indicatriz, que vale 1 si su argumento es cierto y 0 en caso contrario. Definimos el estadístico suficiente $T(y)\in\RR^{k-1}$ mediante
$$
(T(y))_i=\left\{
\begin{array}{cl}
1 & \mbox{si }y=i, \\
0 & \mbox{si }y\neq i.
\end{array}
\right.
$$

Podemos escribir
$$
\begin{align}
p(y\mid\bfphi) &= \phi_1^{(T(y))_1}\phi_2^{(T(y))_2}\ldots\phi_{k-1}^{(T(y))_{k-1}}\phi_k^{1-\sum_{i=1}^{k-1}(T(y))_i} \\[2ex]
&=\exp\left\{\left(\log\left(\frac{\phi_1}{\phi_k}\right), \log\left(\frac{\phi_2}{\phi_k}\right),\ldots, \log\left(\frac{\phi_{k-1}}{\phi_k}\right)\right)^\top T(y)+\log \phi_k\right\}.
\end{align}
$$

Por lo tanto, el parámetro natural es 

$$
\bfeta=\left(\log\left(\frac{\phi_1}{\phi_k}\right), \log\left(\frac{\phi_2}{\phi_k}\right),\ldots, \log\left(\frac{\phi_{k-1}}{\phi_k}\right)\right)^\top\in\RR^{k-1}.
\tag{2.3.10}
$$

<div style="margin-top:1em;"></div>

El resto de los elementos son:
$$
h(y)=1,\qquad A(\bfeta)=-\log\phi_k=-\log\left(1-\sum_{i=1}^{k-1}\phi_i\right).
$$

:::

<div style="margin-top:2em;"></div>

Para este modelo GLM, se tiene
$$
\media\left[T(Y)\mid\xx;\bfphi\right]=\left(\phi_1,\phi_2,\ldots,\phi_{k-1}\right)^\top.
$$



La expresión (2.3.10) es la función de enlace, conocida como *logit generalizado*. Su inversa es la *función softmax* determinada por
$$
\phi_i=\frac{\exp\{\eta_i\}}{1+\sum_{j=1}^{k-1}\exp\{\eta_j\}},\qquad i=1,\ldots,k-1.
$$

El elemento restante de $\bfphi$ se obtiene a partir de la restricción $\sum_{i=1}^k\phi_i=1$, lo cual implica

$$
\phi_k=\frac{1}{1+\sum_{j=1}^{k-1}\exp\{\eta_j\}}.
$$

<div style="margin-top:1em;"></div>



### Modelo

El GLM asociado a la regresión softmax parte de la suposición
$$
\bfeta=\bfTheta^\top\xx,\qquad\bfTheta=\begin{pmatrix}\bftheta_1,\ldots,\bftheta_{k-1}\end{pmatrix}\in\RR^{p\times(k-1)}.
$$

<div style="margin-top:1em;"></div>


Así, la distribución condicional de $Y\mid\XX$ está dada por
$$
p(Y=i\mid\xx;\bfTheta):=\phi_i=\frac{\exp\{\bftheta_i^\top\xx\}}{1+\sum_{j=1}^{k-1}\exp\{\bftheta_j^\top\xx\}},\qquad i=1,\ldots,k-1,
$$
$$
p(Y=k\mid\xx;\bfTheta):=\phi_k=\frac{1}{1+\sum_{j=1}^{k-1}\exp\{\bftheta_j^\top\xx\}}.
\tag{2.3.11}
$$


<div style="margin-top:2em;"></div>


::: {.myhighlight}

El modelo de regresión softmax predice
$$
\hat{y}=(\hat{\phi}_1,\hat{\phi}_2,\ldots,\hat{\phi}_{k-1})^\top.
$$

:::

<div style="margin-top:2em;"></div>



### Optimalidad

El problema de optimización asociado es
$$
\begin{array}{ll}
\text{minimizar } & \displaystyle\sum_{i=1}^n\left[A(\bfeta_i)-\bfeta_i^\top T(y_i)\right].
\end{array}
$$

De (2.3.10) y (2.3.11), podemos escribir la función objetivo como 
$$
J(\bfTheta)=\sum_{i=1}^n\left[\log\left(1+\sum_{j=1}^{k-1}\exp\{\bftheta_j^\top\xx_i\}\right)-\xx_i^\top\bfTheta\, T(y_i)\right].
$$

Derivando respecto a un vector $\bftheta_j$, $j=1,\ldots,k-1$, obtenemos
$$
\begin{align}
\nabla_{\bftheta_j}J(\bfTheta)&=\sum_{i=1}^n\left[\frac{\exp\{\bftheta_j^\top\xx_i\}}{1+\sum_{j=1}^{k-1}\exp\{\bftheta_j^\top\xx_i\}}-(T(y_i))_j\right]\xx_i \\
&=\sum_{i=1}^n\left[\phi_j(\xx_i)-T(y_i)_j\right]\,\xx_i.
\end{align}
$$

Finalmente, resulta
$$
\nabla J(\bfTheta)=X^\top(P-T)\in\RR^{p\times (k-1)},
$$
con
$$
P=\begin{pmatrix}
  \phi_1(\xx_1) & \cdots & \phi_{k-1}(\xx_1) \\
  \phi_1(\xx_2) & \cdots & \phi_{k-1}(\xx_2) \\
  \vdots & \ddots & \vdots \\
  \phi_1(\xx_n) & \cdots & \phi_{k-1}(\xx_n)
\end{pmatrix},\qquad
T = \begin{pmatrix}
(T(y_1))_1 & \cdots & (T(y_1))_{k-1} \\
(T(y_2))_1 & \cdots & (T(y_2))_{k-1} \\
\vdots & \ddots & \vdots \\
(T(y_n))_1 & \cdots & (T(y_n))_{k-1}
\end{pmatrix}
$$

<div style="margin-top:2em;"></div>

Este vector gradiente de la función objetivo puede utilizarse para aplicar el método de descenso por gradiente en regresión softmax. Sin embargo, de acuerdo a lo visto anteriormente, es más adecuado el algoritmo IRLS, para aprovechar la información del Hessiano y generar pasos más precisos y acelerar la convergencia.

<div style="margin-top:1.5em;"></div>


::: {.callout-example}
<span class="badge bg-primary">Ejemplo 2.3.8</span> 
<span style="color: #0d6efd; font-family: Arial; font-weight: bold; font-size: 0.85em;">
Regresión softmax en datos simulados
</span>

Utilizaremos un conjunto de datos simulados para un problema de clasificación con 3 clases, para el cual ajustaremos un modelo de regresión softmax.

::: {.callout-warning appearance="simple"}
En este ejemplo utilizamos la implementación `LogisticRegression` de `scikit-learn`, la cual emplea por defecto el algoritmo LBFGS, un método cuasi-Newton ampliamente utilizado en problemas de optimización convexa. La implementación del algoritmo IRLS se abordará en las actividades prácticas.
:::


```{python}
#| code-summary: "Mostrar código"
#| code-fold: false
#| code-line-numbers: true
#| fig-align: "center"

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Datos:
X, y = make_classification(
    n_samples=300, n_features=2, n_informative=2, n_redundant=0,
    n_classes=3, n_clusters_per_class=1, random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Modelo:
model = LogisticRegression(solver="lbfgs", penalty=None, max_iter=200)
model.fit(X_train, y_train)

# Predicción:
y_pred = model.predict(X_test)
prob_pred = model.predict_proba(X_test)
```

```{python}
#| echo: false
#| fig-align: "center"

# 📈:
# Malla:
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(
    np.arange(x_min, x_max, 0.01),
    np.arange(y_min, y_max, 0.01)
)

Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

# Plot:
plt.figure(figsize=(8,6))
plt.contourf(xx, yy, Z, alpha=0.3, cmap="viridis")
plt.scatter(X[:, 0], X[:, 1], s=40, alpha=0.7, c=y, edgecolor="k", cmap="viridis")
plt.grid(True)
plt.show()


# 📋:
thetas = model.coef_           
intercepts = model.intercept_  

theta_ref = thetas[-1]
intercept_ref = intercepts[-1]

thetas_reduced = thetas[:-1] - theta_ref
intercepts_reduced = intercepts[:-1] - intercept_ref

print("Coeficientes estimados (clase 3 como referencia):")
for i, (coef, b) in enumerate(zip(thetas_reduced, intercepts_reduced), start=1):
    for j, c in enumerate(coef):
        print(f"  θ({i},{j+1}) = {c:.3f}")

print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

```

:::










<br><br>

::: {.refs}
<span style="color: #444;"><strong>Referencias</strong></span>

Ng, A. (2022). *Stanford CS229: Machine Learning - Lecture Notes*. Standford University. 🔗 [ir al sitio web](https://cs229.stanford.edu/notes2022fall/main_notes.pdf).

:::